In [20]:
import pandas as pd
import numpy as np

In [21]:
df = pd.read_csv(r"C:\Users\Pranjal\Downloads\starbucks_customer_ordering_patterns.csv")
df

,customer_id,order_id,order_date,order_time,day_of_week,order_channel,store_id,store_location_type,region,customer_age_group,customer_gender,is_rewards_member,cart_size,num_customizations,total_spend,fulfillment_time_min,drink_category,has_food_item,order_ahead,customer_satisfaction
0,CUST_12974,ORD_00000001,2024-03-25,08:47,Mon,Drive-Thru,STR_340,Suburban,Southwest,18-24,Male,False,5,0,14.48,8.2,Refresher,False,False,4
1,CUST_08235,ORD_00000002,2025-07-18,08:02,Fri,Mobile App,STR_425,Urban,Northeast,35-44,Female,True,1,3,9.52,5.4,Brewed Coffee,False,True,4
2,CUST_00393,ORD_00000003,2025-01-15,05:40,Wed,Kiosk,STR_103,Suburban,Midwest,25-34,Female,False,2,1,9.32,4.9,Brewed Coffee,False,False,5
3,CUST_06936,ORD_00000004,2024-07-30,15:10,Tue,Drive-Thru,STR_318,Suburban,Midwest,25-34,Female,True,2,1,9.55,3.5,Refresher,False,False,4
4,CUST_09800,ORD_00000005,2024-06-18,07:38,Tue,Drive-Thru,STR_338,Suburban,Northeast,35-44,Female,False,3,1,12.24,4.1,Frappuccino,False,False,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,CUST_09857,ORD_00099996,2025-09-17,17:08,Wed,Mobile App,STR_016,Suburban,Northeast,45-54,Non-binary,True,4,0,15.18,3.2,Frappuccino,False,True,4
99996,CUST_09970,ORD_00099997,2024-08-03,08:07,Sat,Drive-Thru,STR_409,Rural,Southwest,35-44,Prefer not to say,True,5,2,16.71,5.5,Espresso,False,False,3
99997,CUST_04417,ORD_00099998,2025-01-11,16:05,Sat,In-Store Cashier,STR_191,Suburban,Northeast,55+,Female,False,3,0,9.12,3.3,Espresso,False,False,1
99998,CUST_07997,ORD_00099999,2025-10-23,18:32,Thu,Mobile App,STR_210,Rural,Southeast,18-24,Female,True,5,1,18.02,1.9,Other,False,False,2
99999,CUST_07625,ORD_00100000,2024-09-01,13:18,Sun,In-Store Cashier,STR_217,Rural,West,55+,Female,False,1,0,5.29,3.1,Brewed Coffee,True,False,5

In [22]:
df.isnull

<bound method DataFrame.isnull of       customer_id      order_id  order_date order_time day_of_week  \
0      CUST_12974  ORD_00000001  2024-03-25      08:47         Mon
1      CUST_08235  ORD_00000002  2025-07-18      08:02         Fri
2      CUST_00393  ORD_00000003  2025-01-15      05:40         Wed
3      CUST_06936  ORD_00000004  2024-07-30      15:10         Tue
4      CUST_09800  ORD_00000005  2024-06-18      07:38         Tue
...           ...           ...         ...        ...         ...
99995  CUST_09857  ORD_00099996  2025-09-17      17:08         Wed
99996  CUST_09970  ORD_00099997  2024-08-03      08:07         Sat
99997  CUST_04417  ORD_00099998  2025-01-11      16:05         Sat
99998  CUST_07997  ORD_00099999  2025-10-23      18:32         Thu
99999  CUST_07625  ORD_00100000  2024-09-01      13:18         Sun

          order_channel store_id store_location_type     region  \
0            Drive-Thru  STR_340            Suburban  Southwest
1            Mobile App  STR_425               Urban  Northeast
2                 Kiosk  STR_103            Suburban    Midwest
3            Drive-Thru  STR_318            Suburban    Midwest
4            Drive-Thru  STR_338            Suburban  Northeast
...                 ...      ...                 ...        ...
99995        Mobile App  STR_016            Suburban  Northeast
99996        Drive-Thru  STR_409               Rural  Southwest
99997  In-Store Cashier  STR_191            Suburban  Northeast
99998        Mobile App  STR_210               Rural  Southeast
99999  In-Store Cashier  STR_217               Rural       West

      customer_age_group    customer_gender  is_rewards_member  cart_size  \
0                  18-24               Male              False          5
1                  35-44             Female               True          1
2                  25-34             Female              False          2
3                  25-34             Female               True          2
4                  35-44             Female              False          3
...                  ...                ...                ...        ...
99995              45-54         Non-binary               True          4
99996              35-44  Prefer not to say               True          5
99997                55+             Female              False          3
99998              18-24             Female               True          5
99999                55+             Female              False          1

       num_customizations  total_spend  fulfillment_time_min drink_category  \
0                       0        14.48                   8.2      Refresher
1                       3         9.52                   5.4  Brewed Coffee
2                       1         9.32                   4.9  Brewed Coffee
3                       1         9.55                   3.5      Refresher
4                       1        12.24                   4.1    Frappuccino
...                   ...          ...                   ...            ...
99995                   0        15.18                   3.2    Frappuccino
99996                   2        16.71                   5.5       Espresso
99997                   0         9.12                   3.3       Espresso
99998                   1        18.02                   1.9          Other
99999                   0         5.29                   3.1  Brewed Coffee

       has_food_item  order_ahead  customer_satisfaction
0              False        False                      4
1              False         True                      4
2              False        False                      5
3              False        False                      4
4              False        False                      3
...              ...          ...                    ...
99995          False         True                      4
99996          False        False                      3
99997          False        False                      1
99998          False        False                      2
99999           True        False                      5

[100000 rows x 20 columns]>

In [23]:
df.isnull().sum()

customer_id              0
order_id                 0
order_date               0
order_time               0
day_of_week              0
order_channel            0
store_id                 0
store_location_type      0
region                   0
customer_age_group       0
customer_gender          0
is_rewards_member        0
cart_size                0
num_customizations       0
total_spend              0
fulfillment_time_min     0
drink_category           0
has_food_item            0
order_ahead              0
customer_satisfaction    0
dtype: int64

In [24]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
99995    False
99996    False
99997    False
99998    False
99999    False
Length: 100000, dtype: bool

In [25]:
df.head()

,customer_id,order_id,order_date,order_time,day_of_week,order_channel,store_id,store_location_type,region,customer_age_group,customer_gender,is_rewards_member,cart_size,num_customizations,total_spend,fulfillment_time_min,drink_category,has_food_item,order_ahead,customer_satisfaction
0,CUST_12974,ORD_00000001,2024-03-25,08:47,Mon,Drive-Thru,STR_340,Suburban,Southwest,18-24,Male,False,5,0,14.48,8.2,Refresher,False,False,4
1,CUST_08235,ORD_00000002,2025-07-18,08:02,Fri,Mobile App,STR_425,Urban,Northeast,35-44,Female,True,1,3,9.52,5.4,Brewed Coffee,False,True,4
2,CUST_00393,ORD_00000003,2025-01-15,05:40,Wed,Kiosk,STR_103,Suburban,Midwest,25-34,Female,False,2,1,9.32,4.9,Brewed Coffee,False,False,5
3,CUST_06936,ORD_00000004,2024-07-30,15:10,Tue,Drive-Thru,STR_318,Suburban,Midwest,25-34,Female,True,2,1,9.55,3.5,Refresher,False,False,4
4,CUST_09800,ORD_00000005,2024-06-18,07:38,Tue,Drive-Thru,STR_338,Suburban,Northeast,35-44,Female,False,3,1,12.24,4.1,Frappuccino,False,False,3

In [26]:
df.drop(columns = ['is_rewards_member','cart_size','num_customizations','fulfillment_time_min','order_ahead'],inplace = True)

In [27]:
df

,customer_id,order_id,order_date,order_time,day_of_week,order_channel,store_id,store_location_type,region,customer_age_group,customer_gender,total_spend,drink_category,has_food_item,customer_satisfaction
0,CUST_12974,ORD_00000001,2024-03-25,08:47,Mon,Drive-Thru,STR_340,Suburban,Southwest,18-24,Male,14.48,Refresher,False,4
1,CUST_08235,ORD_00000002,2025-07-18,08:02,Fri,Mobile App,STR_425,Urban,Northeast,35-44,Female,9.52,Brewed Coffee,False,4
2,CUST_00393,ORD_00000003,2025-01-15,05:40,Wed,Kiosk,STR_103,Suburban,Midwest,25-34,Female,9.32,Brewed Coffee,False,5
3,CUST_06936,ORD_00000004,2024-07-30,15:10,Tue,Drive-Thru,STR_318,Suburban,Midwest,25-34,Female,9.55,Refresher,False,4
4,CUST_09800,ORD_00000005,2024-06-18,07:38,Tue,Drive-Thru,STR_338,Suburban,Northeast,35-44,Female,12.24,Frappuccino,False,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,CUST_09857,ORD_00099996,2025-09-17,17:08,Wed,Mobile App,STR_016,Suburban,Northeast,45-54,Non-binary,15.18,Frappuccino,False,4
99996,CUST_09970,ORD_00099997,2024-08-03,08:07,Sat,Drive-Thru,STR_409,Rural,Southwest,35-44,Prefer not to say,16.71,Espresso,False,3
99997,CUST_04417,ORD_00099998,2025-01-11,16:05,Sat,In-Store Cashier,STR_191,Suburban,Northeast,55+,Female,9.12,Espresso,False,1
99998,CUST_07997,ORD_00099999,2025-10-23,18:32,Thu,Mobile App,STR_210,Rural,Southeast,18-24,Female,18.02,Other,False,2
99999,CUST_07625,ORD_00100000,2024-09-01,13:18,Sun,In-Store Cashier,STR_217,Rural,West,55+,Female,5.29,Brewed Coffee,True,5

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 15 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   customer_id            100000 non-null  object
 1   order_id               100000 non-null  object
 2   order_date             100000 non-null  object
 3   order_time             100000 non-null  object
 4   day_of_week            100000 non-null  object
 5   order_channel          100000 non-null  object
 6   store_id               100000 non-null  object
 7   store_location_type    100000 non-null  object
 8   region                 100000 non-null  object
 9   customer_age_group     100000 non-null  object
 10  customer_gender        100000 non-null  object
 11  total_spend            100000 non-null  float64
 12  drink_category         100000 non-null  object
 13  has_food_item          100000 non-null  bool
 14  customer_satisfaction  100000 non-null  int64
dtypes: bool(1), float64(1), int64(1), object(12)
memory usage: 10.8+ MB

In [29]:
df.describe()

         total_spend  customer_satisfaction
count  100000.000000          100000.000000
mean       14.866771               3.687530
std         5.506800               1.184123
min         3.510000               1.000000
25%        10.837500               3.000000
50%        14.170000               4.000000
75%        18.180000               5.000000
max        40.310000               5.000000

In [30]:
df.to_csv("starbucks_cleaned.csv", index=False)